theme: jekyll-theme-cayman
title: 'UC Davis Bioinformatics Core December 2018 Genome Assembly workshop'
github:
  repository_url: https://ucdavis-bioinformatics-training.github.io/2018-Dec-Genome-Assembly
